### ISSUE TITLE
Computing reading progression

### ISSUE THREAD

**Issue by qnga** [readium/architecture#113]
I think the reading progression defined in a publication should have higher priority than the one guessed from the language, and Epub specification agrees with me. This is currently not the case in [Kotlin implementation](https://github.com/qnga/r2-shared-kotlin/blob/a4b89e0f0178716709a42fe3c6e79664fca12301/r2-shared/src/main/java/org/readium/r2/shared/publication/ContentLayout.kt#L49).

Before the introduction of the new shared model, I changed the computation of reading progression [as here](https://github.com/qnga/r2-shared-kotlin/blob/2e265f96e0b35a398c123ae07c1a23d64e1714bb/r2-shared/src/main/java/org/readium/r2/shared/Metadata.kt#L87).

I suggest we reintroduce my implementation, and document the algorithm in the architecture.

**Comment by HadrienGardeur** [comment]
I think this makes sense but I'd like @JayPanoz to chime in as well since he's the one who authored the EPUB parser guidelines.

**Comment by JayPanoz** [comment]
Yes it should, especially as guessing from language is a fallback in case it isn’t present – because rtl books in epub2 exists for instance, and they won’t pass epubcheck with a `page-progression-direction`, [unless the vendor makes an exception](https://github.com/kobolabs/epub-spec#right-to-left-page-and-text-direction).

[ReadiumCSS has quite a long doc about that](https://github.com/readium/readium-css/blob/master/docs/CSS16-internationalization.md), and in case the `page-progression-direction` is missing, even states: 

> The decision to handle this edge case is up to each implementer, especially as it can be considered a patch of an authoring failure.

Because guessing is complex and has many traps so it would have been a burden to impose this decision to implementers.

**Comment by mickael-menu** [comment]
Since it's part of the Publication models, I'll go ahead and fix this in the Kotlin PR. For Swift, I'll add it here https://github.com/readium/r2-shared-swift/issues/81
