### ISSUE TITLE
Separate the streamer and the navigator concerns

### ISSUE THREAD

**Issue by qnga** [readium/architecture#118]
As far as I know, RWPM has been designed for web publications, that is publications readable by a browser or a Webview. So, by design, the targeted resource formats are those present on the Web.
Though, RWPM is used in R2 as an intermediate publication format between the streamer and the navigator, so, in practice, resources can be of any format allowed in a supported original publication format.

Has it been decided at some point where non-Web resources should been interpreted? 
I think the primary design has been made with Readium Web in mind, so the answer may have been: let's let the streamer deliver ready-to-use Web resources. For instance, CSS injection is currently done by the streamer in Kotlin implementation. However, Michaël and I recently though of moving the Web server to the navigator, and let the app and the navigator set CSS injection.
More in this vein, another approach would be to let the streamer deliver original resources and the navigator interpret them. After all, the navigator can select a resource amongst alternate links according to its own capabilities.

In Kotlin code, we can notice:
- Epub 2.x Ncx table of contents are parsed to a link-based toc in the streamer
- Epub 3.x NavigationDocuments are also parsed in the streamer, though 
> As a fallback mechanism, a Readium Web Publication Manifest may identify an HTML or XHTML resource in `readingOrder` or `resources` as a table of contents using the `contents` link relation.

But tables of contents are quite a special case. Let's look at other cases:
- I think the navigator is intended to display Cbz via native image API, not via a Webview.
- SMIL files were initially supposed to be converted in the streamer into objects close to the Synchronized Narration format and those objects were intended to be stored right inside a `Link` object.

Therefore, it looks like non-Web resources are currently either directly used (Cbz images), or parsed in the streamer.

This theoretical discussion has two immediate applications:
- Where should SMIL files been interpreted? Either in the navigator, or in the streamer. In the latter case, how should resulting objects be retrieved by the navigator? I think making a `Link` directly contain resource data looks quite like a hack. Should rather streamer-made resources been supported? What would be href for them?
- Does the streamer need to access resources, and in particular, encrypted resources? This is an issue in the `Fetcher` design. With the actual design, resources are decrypted by the `Fetcher`, but this same object is instantiated with a ready-to-use `Publication`. Therefore, it cannot be used while making `Publication` object, the main concern of the streamer in the approach Mickaël and I though of. LCP forbids encryption of navigation data, but other encryption schemes don't, and even LCP doesn't forbid encrypted SMIL files.

**Comment by llemeurfr** [comment]
> I think the primary design has been made with Readium Web in mind
> let's the streamer deliver ready-to-use Web resources

As EPUB 3 means XHTML/CSS/JS, the primary design has been that an HTML navigator would be based on a webview; this is true for all implementations (Readium Web, Mobile and Desktop).   
Also, large media (audio/video) should be processed by chunks (progressive download) to avoid filling the memory of the device, therefore having a Web server on the streamer side is sensible (again for Web oriented formats like EPUB). 

 > the navigator is intended to display Cbz via native image API

maybe no "the" navigator but "a" navigator. From the start we imagined a set of navigators like a swiss army knife: the app chooses the best one for a given purpose. 

A basis of previous decisions was that there are many publication formats out there; a parser transforms an external format into the internal Readium format, i.e. the Webpub Manifest and a navigator uses this format. If the navigator is based on a webview, it is fed via a streamer, i.e a web server serving a webpub manifest and associated resources via http GET. From this pattern, we can imagine several ways to create content workflows in our toolkits. 

> LCP doesn't forbid encrypted SMIL files

If this absence of constraint causes issues, we can add such constraint. 

Hope it can help in this discussion.

**Comment by qnga** [comment]
> maybe no "the" navigator but "a" navigator. From the start we imagined a set of navigators like a swiss army knife: the app chooses the best one for a given purpose.

I often hear about multiple navigators, but I think Michaël is going to suggest a unique global navigator. It would release the app from the job of choosing a navigator, and would be more flexible: in principle, a "view" has to be chosen for each readingOrder resource, not once and for all for a full publication. I guess Michaël will soon argue for that in more details.

> A basis of previous decisions was that there are many publication formats out there; a parser transforms an external format into the internal Readium format, i.e. the Webpub Manifest and a navigator uses this format.

Ok, so far, everybody agrees. The navigator should not have to be aware of the original publication format, but use RWPM instead. But what about original resource format?

**Comment by mickael-menu** [comment]
> As far as I know, RWPM has been designed for web publications, that is publications readable by a browser or a Webview.

It's meant for publications that can be distributed over HTTPS, but not necessary for resources only readable by browsers.

> For instance, CSS injection is currently done by the streamer in Kotlin implementation. However, Michaël and I recently though of moving the Web server to the navigator, and let the app and the navigator set CSS injection.

There's still a need to handle injection at the streamer level – with content filters, [as I mentioned here](https://github.com/readium/r2-navigator-swift/issues/105#issuecomment-590766034) – for example to avoid re-layout when applying custom CSS or to be used by mobile apps using a JS framework for the UX.

However, I believe that the streamer should not inject CSS or JS by default. The resources to be injected should be provided by the navigator.

We can argue that the CF would not be part of the streamer API anymore, since they would be in shared and used across the different libraries as a binding interface. But it's a technical separation, theoretically reading the resources is done in the Streamer through a Fetcher, and presenting the resources is done in the Navigator.

> Therefore, it looks like non-Web resources are currently either directly used (Cbz images), or parsed in the streamer.

It's not so much about being a web resource or not. The actual content of the publication must be accessed directly (so images, HTML, audio, PDF). But `SMIL` files are not content, they are metadata around the actual content, therefore it makes sense that the streamer parse it as metadata into a shared RWPM model.

> Where should SMIL files been interpreted? Either in the navigator, or in the streamer. In the latter case, how should resulting objects be retrieved by the navigator? I think making a Link directly contain resource data looks quite like a hack. Should rather streamer-made resources been supported? What would be href for them?

There's a case for loading the sync narration resources in the navigator, instead of immediately when parsing the `Publication`, since they will be used by the navigator. However, I think that the streamer should handle the transformation of whatever original format (e.g. SMIL) into a shared model understandable by the Navigator, whether it's part of `Link` or not.

> Does the streamer need to access resources, and in particular, encrypted resources? This is an issue in the Fetcher design.

Usually metadata (title, cover, etc.) are not encrypted, so we should be able to parse a `Publication` even if we can't decrypt the content. For other resources such as SMIL, that's another case for loading them later, when they are actually required and we have the DRM license.

> maybe no "the" navigator but "a" navigator. From the start we imagined a set of navigators like a swiss army knife: the app chooses the best one for a given purpose.

> I often hear about multiple navigators, but I think Michaël is going to suggest a unique global navigator. It would release the app from the job of choosing a navigator, and would be more flexible

We talked a bit about this subject during the last dev call, but until there's a proposal ready for the evolution of the navigator ("the" as the navigator layer here), I'll clarify a bit my vision for the navigator here.

From the start R2 was designed as a set of interchangeable components, so an app can use several implementations of the navigator layer.

Currently, the official navigator lib is exposing one `Navigator` (type) per publication format (so EPUB/HTML, CBZ/Image, PDF, Audiobook, etc.). But I think we should move away from publication formats, since a `Publication` is not limited to only one media type for its resources. Instead, we would have a single `Navigator` type, which would present each resource using media-type specific `ResourceAdapter`s. The reading apps should be able to provide custom `ResourceAdapter`s to the `Navigator` to present additional media-types seamlessly.

The responsibilities become clearer:
- `ResourceAdapter` renders a specific media-type and offer an interface for media-type specific features (e.g. CSS/JS injection for HTML, time for audio files, etc.)
- `Navigator` orchestrates the `ResourceAdapter` presentation to handle the navigation through the reading order, and offer a unified API for navigation (using mainly `Locator`). It also handles the Presentation Hints and spreads.

Now, I think we could actually have several `Navigator` types, to provide different paradigm of navigation. For example, it makes sense to paginate or scroll through a multi-media type publication, or an EPUB publication. But if the reading app knows that the publication is actually an audiobook, then it might prefer to present it in a non-scrollable way, with a single view on-screen showing the cover, for example.

Alternatively, it might be better to have a single `Navigator` handling the creation of the `ResourceAdapter`s and the navigation with the `Locator`, but several `LayoutManager` types handling the presentation of the `ResourceAdapter`s.

> Ok, so far, everybody agrees. The navigator should not have to be aware of the original publication format, but use RWPM instead. But what about original resource format?

For content resources, the navigator needs to understand the media-type to be able to render it. But for other resources such as SMIL, it shouldn't need to.

**Comment by qnga** [comment]
> But SMIL files are not content, they are metadata around the actual content, therefore it makes sense that the streamer parse it as metadata into a shared RWPM model.

I think this point of view can be challenged. During a call, a `Link` property called "syncNarration" and pointing to a media overlays resource has been discussed and dropped. As far as I can remember, @HadrienGardeur argued that media overlays were primary resources the navigator could choose amongst all possible `alternate`. Media overlays are just as much self-contained like HTML files: they don't include everything, but do reference everything. In my mind, this makes media overlays first-class resources that should be delivered by the streamer, via the fetcher, and in any format.

> For content resources, the navigator needs to understand the media-type to be able to render it. But for other resources such as SMIL, it shouldn't need to.

Let's imagine that we want to support a font file format that is not supported by the Webview. This is a non-content secondary resource. Do you really think the format conversion should occur in the streamer? It looks like a workaround for an issue with the navigator's implementation details.

**Comment by mickael-menu** [comment]
> Media overlays are just as much self-contained as HTML files: they don't include everything, but do reference everything. In my mind, this makes media overlays first-class resources that should be delivered by the streamer, via the fetcher, and in any format.

It may be, I'm not super familiar with SMIL. To me it looks more like some kind of manifest linking resources together. In that sense, it can be seen as a primary "view" of the actual content that the navigator could use, but that doesn't need that the navigator is responsible for parsing it.

> Let's imagine that we want to support a font file format that is not supported by the Webview. This is a non-content secondary resource. Do you really think the format conversion should occur in the streamer? It looks like a workaround for an issue with the navigator's implementation details.

No it wouldn't be converted. Fonts are part of the content as well in my opinion, same as images that would be included in an HTML resource in an unknown format.

**Comment by mickael-menu** [comment]
@qnga Can we close this issue? It's a bit confusing with a lot of crossing subjects. I suggest opening more specific issues or even [proposals](https://github.com/readium/architecture/issues/128) as problems arise (e.g. regarding SMIL parsing)

Regarding the 2 initial questions, let's conclude:

> Where should SMIL files been interpreted? Either in the navigator, or in the streamer. In the latter case, how should resulting objects be retrieved by the navigator? I think making a Link directly contain resource data looks quite like a hack. Should rather streamer-made resources been supported? What would be href for them?

I think that the majority view is to avoid parsing SMIL directly in the navigator. A `PublicationService` is a good candidate to have the models outside the RWPM. But we can open a specific issue/proposal when the time to implement Media Overlays arise.

> Does the streamer need to access resources, and in particular, encrypted resources? This is an issue in the Fetcher design. With the actual design, resources are decrypted by the Fetcher, but this same object is instantiated with a ready-to-use Publication. Therefore, it cannot be used while making Publication object, the main concern of the streamer in the approach Mickaël and I though of. LCP forbids encryption of navigation data, but other encryption schemes don't, and even LCP doesn't forbid encrypted SMIL files.

This is outdated with our upcoming proposal on DRM management.

**Comment by qnga** [comment]
> I think that the majority view is to avoid parsing SMIL directly in the navigator. A PublicationService is a good candidate to have the models outside the RWPM. But we can open a specific issue/proposal when the time to implement Media Overlays arise.

I am still not convinced, but we'll be able to talk about that later elsewhere, indeed.
