### ISSUE TITLE
Strategy for Building a web-based Reader from the current prototypes

### ISSUE THREAD

**Issue by rkwright** [readium/architecture#74]
There are currently three efforts underway to create a "R2" like Web-based Reader (successor to the R1 CloudReader)

- Readium Web (nee NG, driven by Evident Point)
- NYPL WebReader prototype
- A collaboration between Jellybooks and Jiminy

The question is how or if to combine these efforts.  In order to do this, we need come up with a good high level spec of what we are building, what each of the above efforts brings to the table and so on.

**Comment by JayPanoz** [comment]
An important note there: in terms of concepts and architecture, we didn’t change anything in NYPL Reader, that we chose as it’s super lightweight, configurable, and can work in a lot of contexts – in some you don’t need a fully-fledged reader for instance, only a barebones one.

It’s also fast, which is something we’re paying attention to because of some contexts: first meaningful paint on initial load is 2.7 seconds, 1.7 seconds on subsequent ones, in real life – and we haven’t started epics on performance yet. 

We’ve been simply building on top of it, upgrading the dependencies, fixing a few bugs and adding a few features. As regards the R2-Architecture, to sum the state of my affairs, triptych view we don’t have yet, nor ReadiumCSS, nor r2-Glue-js – our interest is also in collaborating with others and contributing to that (esp. today, as I had to deal with keyboard events alone).

**Comment by JCCR** [comment]
@JayPanoz 
Thanks for sharing your perspective. 
I personally like the idea of a super lightweight implementation for the web. 
Readium Web isn't lightweight like that right now because of our approach to the goal of being able to implement fully-fledged reader.

Being fast is a part of that goal too.
I believe we are being quick and responsive.. but only after the bootstrapping. 
We've only reached the point now where we can start paying close attention to the time it takes to load and to get to a first meaningful paint.

I'm happy to hear about the interest in collaboration! 
I'll continue that effort with more contributions to r2-glue-js

(and thank you @rkwright for starting this issue)

**Comment by JayPanoz** [comment]
Yeah we’ve been trying to find how to contribute our shareable commits back for almost two weeks. It’s been quite an adventure, with (literally) thousands of emails to get a better grasp at the current situation. 

Can confirm we’re also using the r2-streamer-js, as you may well know ;-)

**Comment by aslagle** [comment]
My goal when I worked on NYPL's reader was to make individual components configurable, so basic or more full-fledged components could be swapped in depending on an application's needs.

I haven't had time to look at Readium Web closely but I'd love to see if these approaches can be combined somehow.

**Comment by JayPanoz** [comment]
@aslagle That was definitely a killer-feature to us because we have various use cases, so many thanks for that. 👍

**Comment by HadrienGardeur** [comment]
I think the strategy should be similar to the mobile apps, except that for Readium Web, we don't have to start from the streamer (it's not always necessary to have one) but instead focus on:

- a shared model
- code for parsing the Readium Web Publication Manifest (and ideally, WP as well)
- a navigator

From there, we can build a test app that integrates all three together, most likely using Readium CSS and Glue JS.

For each of the current prototype, we need to look at their strategy for handling these three components.

For the navigator, IMO the right strategy is to:

- somehow replicate the triptych view using multiple iframes (doesn't have to be three though)
- use `srcdoc` rather than `src`
- offer the ability to easily inject additional JS/CSS resources through an API
- automatically inject CSS Custom Properties based on what's in the shared model

**Comment by llemeurfr** [comment]
To start with requirements, IMO the resulting code should
- be highly modular, allowing the generation of basic to full-fledged reading apps (modularity)
- be equally efficient in multiple browsers (interoperability)
- allow processing of Readium Web Publications, exploded EPUBs and W3C Web Publications - other formats may be supported via extensions (versatility).

**Comment by arhomberg** [comment]
I would like to address two points of confusion::

(1) there are not three reference models for building a cloud reader, but only **two**. The Jellybooks version, which @JayPanoz built (he is part of the Jellybooks team) is an upgraded and dare i say somewhat "improved" version of the NYPL web reader, which is more commonly referred to as "Simply E" and which is a component of "Library Simplified"

(2) We at Jellybooks never set out to build a "R2-like Web-based Reader", we simply wanted to build a simple, light-weight cloud reader that met our needs and do so using open-source software. The criterion was to do this **now** and start piloting actual use cases as soon as possible. The NYPL web reader/Simply E fit the bill perfectly, because it was lightweight, modular, easy to configure, open source and available under an Apache license. Based on reactions during the past few days, I would way that we are not the only ones with that mindset/combination of needs.

Oh and our cloud reader based on Simply E is deployed as a private (but working) alpha using a R2 based streamer (hosted on Linode using npm and controlled by our Rails platform). We reached that milestone after last week's call. We will be going into public beta in a few weeks time..

**Comment by HadrienGardeur** [comment]
> Also the principles of modularity, ease of use and "pick and mix" would be very critical going forward, so that the code-base can cater to anything from "lightweight" to demanding, highly specialized applications.

@arhomberg 

This is at the very core of the new Readium architecture. Most modules interact together using the shared model, but aside than that you can pick and chose what you'd like to use.

Over the last 18 months, we've made a lot of progress in that direction and as a first step, we need to look back at how various projects implement this modularity.

**Comment by danielweck** [comment]
@HadrienGardeur 
>  using `src` is good enough (etc.) ... 
(quoted content clipped)

Yes, and `src` + `BlobURI` can be used instead of `srcdoc` (just as we do in Readium "1") *if*  the client-side frontend code (i.e. browser runtime) *really* needs to manipulate HTML/SVG document data (supplied by the streamer / HTTP response bodies) before the data actually reaches the iframes. Another option is also to proxy responses through Service Worker(s), and use regular URLs in the `src` attribute.

**Comment by HadrienGardeur** [comment]
@danielweck indeed, there are multiple alternatives when `src` + a URI is not good enough.

A full navigation module will most likely need to handle both cases.

**Comment by JayPanoz** [comment]
@JCCR No worries, I well know those “features” are also some of your goals and the demo you made was pretty impressive in its current state. 👍 

Do not hesitate to mail me if you have questions related to the elements or architecture choices we like in the NYPL Reader. I’m obviously not as familiar to all its details and inwards as @aslagle but I’m slowly getting there. 

As Andrew said, ”We at Jellybooks never set out to build a R2-like Web-based Reader, we simply wanted to build a simple, light-weight cloud reader that met our needs.” Timing has been unfortunate to some extent, but we’ve learnt a lot so I’ll be happy to share those (mainly technical right now) findings as well.

**Comment by JayPanoz** [comment]
I’ve also been reporting wrong performance metrics for some reason so I edited my first message. 

After some check, Initial load is 1.7 seconds, 1 second on subsequent ones (without minifying assets).
