### ISSUE TITLE
Parsing a subtitle

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/architecture#80]
It seems that while `title` and `sortAs` are covered in the new parsing document, that's not the case for `subtitle`: https://github.com/readium/architecture/blob/master/streamer/parser/metadata.md

cc @JayPanoz

**Comment by JayPanoz** [comment]
Ah yes, good catch. I was unsure about this one as there is no mapping in [appendix B for EPUB 3.1](https://github.com/readium/webpub-manifest/tree/master/contexts/default#appendix-b---mapping-to-schemaorg--epub-31) and a bunch of other keys e.g. `letterer` so I may have dropped some of those because of that in the initial document. 

Maybe before I PR that, it could be a good idea to define which missing items should be handled in this doc? 

Currently: 

- subtitle
- inker
- penciler
- letterer
- imprint
- numberOfPages
- duration

**Comment by HadrienGardeur** [comment]
The appendix is probably not entirely up-to-date and it was based on EPUB 3.1, whereas we should primarily focus on 3.2 now.

For the contributors (`inker`, `penciler` and `letterer`), I think the main issue was that I couldn't identify the proper MARC relator codes for them.

For `numberOfPages`, I think that in EPUB 3.2 at least, the recommendation is to use schema.org as well.

`duration` is handled in [EPUB Media Overlay](http://www.idpf.org/epub/31/spec/epub-mediaoverlays.html#sec-package-metadata) for which we also need to handle a specific case for `narrator`.
`active-class` and `playback-active-class` are not currently handled in RWPM, I'll let @danielweck chime in on that.

As for `imprint`, we can probably ignore it for now in the context of EPUB.

**Comment by JayPanoz** [comment]
Thanks, let me take a look for everything but media overlays. I can probably PR that shortly.

**Comment by JayPanoz** [comment]
So yeah inker, penciler and letterer are missing in [relator codes](https://www.loc.gov/marc/relators/relaterm.html), as confirmed in [this w3c mail](https://lists.w3.org/Archives/Public/public-vocabs/2014Sep/0011.html), and looks like [some people use `illustrator` for that](https://www.mail-archive.com/rda-l@listserv.lac-bac.gc.ca/msg09173.html).

From the last link… I guess we really don’t want to go down this rabbit hole for `letterer`: 

> I've been using "illustrator" for some of these (penciller, inker, cover artist) but *I use 
"calligrapher" for letterers* and "colorist" for colorists.

**Comment by HadrienGardeur** [comment]
We probably don't want to go down that rabbit road for any of them if there's no exact equivalent. They'll end up in `contributor`, which is fine.
